# Docker Compose for an ARR media stack
# Includes: Prowlarr (indexers), Radarr (movies), Sonarr (TV),
# qBittorrent (torrent client), Recyclarr (TRaSH sync), FlareSolverr (CF bypass).
# Uses an external Traefik network and an internal media bridge.
networks:
  traefik:
    name: "traefik"
    external: true
    # External reverse-proxy network; must exist beforehand (e.g., Traefik stack)
  media:
    name: "media"
    driver: bridge
    # Private bridge for inter-service traffic and file sharing

volumes:
  prowlarr:
  radarr:
  sonarr:
  qbittorrent:
  # Named volumes store app configurations; media paths are host bind mounts
  
services:
  # Prowlarr: indexer aggregator/proxy for Radarr/Sonarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    # Exposes Prowlarr web UI
    ports:
      - 9696:9696
    security_opt:
      - no-new-privileges:true
    # Run apps with non-root UID/GID and set timezone
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # Persist config and mount downloads/media directories
    volumes:
      - prowlarr:/config
    networks:
      # Attach to Traefik and internal media networks
      - traefik
      - media

  # Radarr: movie library management/automation
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    # Exposes Radarr web UI
    ports:
      - 7878:7878
    security_opt:
      - no-new-privileges:true
    # Run apps with non-root UID/GID and set timezone
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # Persist config and mount downloads/media directories
    volumes:
      - radarr:/config
      - ${MEDIA}/downloads:/data/downloads:rw
      - ${MEDIA}:/media:rw
    networks:
      # Attach to Traefik and internal media networks
      - traefik
      - media
      
  # Sonarr: TV library management/automation
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    # Exposes Sonarr web UI
    ports:
      - 8989:8989
    security_opt:
      - no-new-privileges:true
    # Run apps with non-root UID/GID and set timezone
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # Persist config and mount downloads/media directories
    volumes:
      - sonarr:/config
      - ${MEDIA}/downloads:/data/downloads:rw
      - ${MEDIA}:/media:rw
    networks:
      # Attach to Traefik and internal media networks
      - traefik
      - media

  # Recyclarr: sync Radarr/Sonarr settings with TRaSH guides
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    init: true
    # Minimal env; runs as the media user
    environment: 
      - TZ=${TZ}
    user: ${PUID}:${PGID}
    # Local config folder for Recyclarr YAMLs and cache
    volumes:
      - ./recyclarr-app:/config

  # FlareSolverr: helper to bypass Cloudflare for some indexers
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    # Exposes FlareSolverr service port, not required, uncomment to allow.
    #ports:
    # -8191:8191
    networks:
      - media

    # qBittorrent: torrent client (WebUI on 8080)
    qbittorrent:
      container_name: qbittorrent
      image: lscr.io/linuxserver/qbittorrent:latest
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      # Light memory cap to prevent overuse
      deploy:
        resources:
          limits:
            memory: 512M
      # Web UI, torrenting ports, and runtime user settings
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        - WEBUI_PORT=8080
        - TORRENTING_PORT=6881
      # Expose Web UI and torrent ports (TCP/UDP)
      ports:
        -  8080:8080
        -  6881:6881
        -  6881:6881/udp
      networks:
       - traefik
       - media
      # Persist qBittorrent config and share downloads/media
      volumes:
        - qbittorrent:/config
        - ${MEDIA}/downloads:/data/downloads:rw

