networks:
  traefik:
    name: "traefik"
    external: true
  media:
    name: "media"
    driver: bridge

volumes:
  prowlarr:
  radarr:
  sonarr:
  
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr:/config
      - ${MEDIA}/downloads:/data/downloads:rw
      - ${MEDIA}:/media:rw
    networks:
      - traefik
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - radarr:/config
      - ${MEDIA}/downloads:/data/downloads:rw
      - ${MEDIA}:/media:rw
    networks:
      - traefik
      - mdeia
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr:/config
      - ${MEDIA}/downloads:/data/downloads:rw
      - ${MEDIA}:/media:rw
    networks:
      - traefik
      - media

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    init: true
    environment: 
      - TZ=${TZ}
    user: ${PUID}:${PGID}
    volumes:
      - ./recyclarr-app:/config